/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__pyatom
#define __PYX_HAVE__pyatom


#ifndef __PYX_HAVE_API__pyatom

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) PythonPrint(char const *);

#endif /* !__PYX_HAVE_API__pyatom */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyatom(void);
#else
PyMODINIT_FUNC PyInit_pyatom(void);
#endif

#endif /* !__PYX_HAVE__pyatom */
