// config files
// THIS FILE IS AUTOMATICALLY GENERATED BY param.py
// ANY CHANGES WILL BE OVERWRITTEN AT COMPILE TIME

#include"AtmParameters.h"
namespace AtmParameters{

  // common section
  string bathymetry_path;
  string BathymetrySuffix;
  bool verbose;
  string output_path;
  bool paraview_panorama_vts;
  bool debug;
  string temperature_file;
  string precipitation_file;
  string salinity_file;
  string temperature_curve_file;
  string reconstruction_script_path;
  bool use_earthbyte_reconstruction;
  int time_start;
  int time_end;
  int time_step;

  // atmosphere section
  int velocity_iter_max_2D;
  int pressure_iter_max_2D;
  int velocity_iter_max;
  int pressure_iter_max;
  int checkpoint;
  double WaterVapour;
  double Buoyancy;
  double CO2;
  double epsres;
  int sun;
  int NASATemperature;
  int RadiationModel;
  int declination;
  int sun_position_lat;
  int sun_position_lon;
  int Ma_max;
  int Ma_max_half;
  double L_atm;
  int tropopause_pole;
  int tropopause_equator;
  double rad_equator;
  double rad_pole;
  double sigma;
  double albedo_pole;
  double albedo_equator;
  double epsilon_equator;
  double epsilon_pole;
  double epsilon_tropopause;
  double re;
  double sc_WaterVapour;
  double sc_CO2;
  double pr;
  double g;
  double ep;
  double hp;
  double R_Air;
  double r_air;
  double R_WaterVapour;
  double r_water_vapour;
  double R_co2;
  double lv;
  double ls;
  double cp_l;
  double lamda;
  double r_co2;
  double gam;
  double u_0;
  double p_0;
  double t_0;
  double c_0;
  double co2_0;
  double ua;
  double va;
  double wa;
  double pa;
  double ca;
  double ta;
  double coa;
  double t_cretaceous_max;
  double t_cretaceous;
  double t_average;
  double t_equator;
  double t_pole;
  double t_tropopause;
  double t_land;
  double c_tropopause;
  double c_ocean;
  double c_land;
  double co2_average;
  double co2_equator;
  double co2_tropopause;
  double co2_pole;
  double co2_cretaceous;
  double co2_vegetation;
  double co2_ocean;
  double co2_land;
  double co2_factor;
}
